# Generated by Django 3.2.9 on 2021-12-16 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20211216_1745'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('billing_number', models.BigIntegerField(primary_key=True, serialize=False)),
                ('customer', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('purchase_date', models.DateTimeField()),
                ('company', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('serial_number', models.BigIntegerField()),
                ('mfg_date', models.DateTimeField()),
                ('shipping_date', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
